# .github/workflows/update_data.yml

name: Update IPTV Data

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

# AQUI ESTÁ A CORREÇÃO: Damos permissão para a Action escrever no repositório
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch data from API
        env:
          API_SPORTS_KEY: ${{ secrets.API_SPORTS_KEY }}
        run: python fetch_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add data/
          # Só faz o commit se houver mudanças
          git diff --staged --quiet || git commit -m "Update data files"
          git push
